apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 425920741281.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 425920741281.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 3e08e238
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
